apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
      - name: api-gateway-app
        image: kattasaiteja/apigateway:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8765
        env:
          - name: EUREKA_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app
spec:
  selector:
    app: api-gateway-app
  ports:
  - port: 80
    targetPort: 8765
