name: Build & Push cloud demo

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-demo/**'
  workflow_dispatch:
# permission for gradle build

jobs:
  build-booking-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        
      - name: Build & Push Docker Image with Jib
#        working-directory: ./cloud-demo
        run: ./gradlew jib :cloud-demo:jib
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

