name: Build & Push Docker Images

on:
  push:
    branches:
      - main
    workflow_dispatch:
    paths:
      - 'apigateway/**'


jobs:
  build-apigateway:
    if: contains(join(github.event.head_commit.modified), 'apigateway/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push API Gateway Docker Image
        run: |
          docker build -t your-dockerhub-username/apigateway:latest ./apigateway
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-dockerhub-username/apigateway:latest
